import '../styles/globals.scss'
import MyDrawer from '../componants/MyDrawer';
import Head from 'next/head'
function MyApp({ Component, pageProps }) {
  return <> 
      <Head>
        <title>Omkar Shinde Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      
      </Head>
      
   <MyDrawer Component={Component} pageProps={pageProps} />    
  {/* <Component {...pageProps} />  */} 
  </>
}

export default MyApp
