import '../styles/globals.scss'
import Head from 'next/head'
function MyApp({ Component, pageProps }) {
  return <> 
      <Head>
        <title>Omkar Shinde Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Component {...pageProps} />  
  </>
}

export default MyApp
